name: Build Executable

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build Executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      #      - name: Build JAR
      #        run: ./gradlew packageReleaseUberJarForCurrentOS

      #      - name: Upload JAR
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: admin.jar
      #          path: build/compose/jars/*.jar

      - name: Build DEB
        run: ./gradlew packageDeb

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: admin.deb
          path: build/compose/binaries/main/deb/*.deb

      - name: Build MSI
        run: ./gradlew packageMsi

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: admin.msi
          path: build/compose/binaries/main/msi/*.msi